name: Update Curve Strategies

on:
  workflow_dispatch:

env:
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  ARBISCAN_TOKEN: ${{ secrets.ARBISCAN_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
    
      - name: Run script to update Curve Strategies data
        run: pnpm tsx scripts/strategies/execute.ts curve

      - name: Commit and push if changes found
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Stake DAO API update"
          git add api/strategies/curve
          git commit -m "$(date +"%Y-%m-%d %H:%M:%S"): Auto-update Curve strategies data"
          git push
        shell: bash


