name: Update Strategies

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes

env:
  ETHERSCAN_TOKEN: {{ secrets.ETHERSCAN_TOKEN }}
  PUBLIC_RPC_MAINNET: https://eth.public-rpc.com

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
    
      - name: Run script to update Strategies data
        run: pnpm tsx scripts/fetch.ts

      - name: Commit and push if changes found
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Stake DAO API update"
          git add api/strategies/*.json
          git diff --quiet --exit-code || git commit -m "Auto-update strategies data $(date +%Y-%m-%d)"
          git push

