name: Update Votium merkles

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * 2' # Every Tuesday at 8:30 am, filtered later to match distributions

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Verify week number # Votium distributions occurs on odd weeks
        run: |
          week_number=$(date +%V)
          if [ $((week_number % 2)) -eq 0 ]; then
            echo "Updating script"
          else
            echo "Wrong week, aborting..."
            exit 0
          fi
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run script to update Votium Merkles data
        run: pnpm tsx scripts/votemarket/updateVotiumMerkles.ts

      - name: Commit and push if changes found
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Stake DAO API update"
          git add api/votemarket/votium_merkles.json
          git commit -m "$(date +"%Y-%m-%d %H:%M:%S"): Auto-update Votium merkles data"
          git push
        shell: bash
