name: Update Votemarket Proofs (current week)

on:
  schedule:
    - cron: "0 2 * * 4" # Every Thursday at 02:00 UTC
  workflow_dispatch:

env:
  ETHEREUM_MAINNET_RPC_URL: ${{ secrets.ETHEREUM_MAINNET_RPC_URL }}
  ARBITRUM_MAINNET_RPC_URL: ${{ secrets.ARBITRUM_MAINNET_RPC_URL }}
  GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run active users proofs script
        run: make -f automation/get_active_users_proofs.mk

      - name: Move generated JSON files
        run: |
          current_period=$(date +%s)
          current_period=$((current_period - current_period % (7 * 24 * 3600)))
          mkdir -p api/votemarket/proofs/$current_period
          mv temps/votemarket-proofs-script/temp/*_active_proofs.json api/votemarket/proofs/$current_period/

      - name: Commit and push if changes found
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Stake DAO API update"
          git add api/votemarket/proofs
          git commit -m "$(date +"%Y-%m-%d %H:%M:%S"): Auto-update Votemarket proofs data"
          git push
        shell: bash


